name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env: 
  API_KEY: ${{ vars.API_KEY }}
jobs:
  Run-Python-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Get Python version
        run: python --version
      - name: Run script
        run: python env.py 
